// demo-data.js
// Banco de dados estático local para a versão de demonstração (Portfólio)
// Este arquivo é a "fonte da verdade" inicial e alimenta o localStorage.

window.INITIAL_DEMO_DATA = {
    // Lista de Astrônomos (usuários comuns)
    astronomos: [
        {
            id_astronomo: 1,
            usuario: "astronomo",
            nome_completo: "Dr. Arthur Lira",
            cidade_base: "São Paulo - SP",
            consumo_km_l: 10,
            valor_litro: 5.80,
            diaria_hospedagem: 250,
            alimentacao_diaria: 60,
            monitor: 120,
            percentual_lucro: 15,
            porcentagem_lucro: 15,
            lucro_percentual: 15
        },
        {
            id_astronomo: 2,
            usuario: "helena",
            nome_completo: "Dra. Helena Souza",
            cidade_base: "Campinas - SP",
            consumo_km_l: 12,
            valor_litro: 5.80,
            diaria_hospedagem: 200,
            alimentacao_diaria: 50,
            monitor: 100,
            percentual_lucro: 12,
            porcentagem_lucro: 12,
            lucro_percentual: 12
        },
        {
            id_astronomo: 3,
            usuario: "lucas",
            nome_completo: "Lucas Neto",
            cidade_base: "Rio de Janeiro - RJ",
            consumo_km_l: 9,
            valor_litro: 6.10,
            diaria_hospedagem: 300,
            alimentacao_diaria: 70,
            monitor: 130,
            percentual_lucro: 18,
            porcentagem_lucro: 18,
            lucro_percentual: 18
        }
    ],

    // Lista de administradores do painel de RH
    admins: [
        {
            id_admin: 1,
            usuario: "admin",
            email: "admin@urania.example",
            senha: "admin",
            role: "admin"
        }
    ],

    // Lista global de Eventos
    eventos: [
        // --- Eventos operacionais do calendário (Junho de 2026) ---
        {
            id: "ev_101",
            id_evento: "ev_101",
            nome_da_escola: "Colégio Stellar",
            cidade: "Campinas - SP",
            cidade_destino: "Campinas - SP",
            tipo_da_tarefa: "VISITA",
            tipo_evento: "VISITA",
            data_agendamento: "2026-06-21T09:00:00",
            data_e_hora_agendamento: "2026-06-21T09:00:00",
            responsavel_pelo_evento: "Prof. Carlos Cruz",
            responsavel: "Prof. Carlos Cruz",
            telefone_contato: "(19) 98765-4321",
            numero_alunos: "120",
            numero_de_alunos: "120",
            valor_total: 2500,
            total: 2500,
            conteudo_da_apresentacao: "Foguetes e Órbitas",
            finalizado: false,
            finalizada: false,
            latitude_origem: -23.5505,
            longitude_origem: -46.6333,
            latitude_destino: -22.9099,
            longitude_destino: -47.0626,
            origem_lat: -23.5505,
            origem_lon: -46.6333,
            destino_lat: -22.9099,
            destino_lon: -47.0626,
            distancia_estimada_km: 98,
            distancia: "98 km",
            id_astronomo: 1,
            observacoes: "Levar telescópio solar Coronado para atividade prática no pátio."
        },
        {
            id: "ev_102",
            id_evento: "ev_102",
            nome_da_escola: "Instituto Galileo",
            cidade: "São José dos Campos - SP",
            cidade_destino: "São José dos Campos - SP",
            tipo_da_tarefa: "VISITA",
            tipo_evento: "VISITA",
            data_agendamento: "2026-06-22T10:00:00",
            data_e_hora_agendamento: "2026-06-22T10:00:00",
            responsavel_pelo_evento: "Diretora Márcia",
            responsavel: "Diretora Márcia",
            telefone_contato: "(12) 98122-3344",
            numero_alunos: "80",
            numero_de_alunos: "80",
            valor_total: 1800,
            total: 1800,
            conteudo_da_apresentacao: "Constelações e Mitologia",
            finalizado: false,
            finalizada: false,
            latitude_origem: -23.5505,
            longitude_origem: -46.6333,
            latitude_destino: -23.1791,
            longitude_destino: -45.8872,
            origem_lat: -23.5505,
            origem_lon: -46.6333,
            destino_lat: -23.1791,
            destino_lon: -45.8872,
            distancia_estimada_km: 94,
            distancia: "94 km",
            id_astronomo: 1,
            observacoes: "Apresentação no auditório climatizado."
        },
        // --- Viagem de Rota Contínua no Vale do Paraíba (Consecutivos) ---
        {
            id: "ev_103",
            id_evento: "ev_103",
            nome_da_escola: "Escola Estrela Guia",
            cidade: "Taubaté - SP",
            cidade_destino: "Taubaté - SP",
            tipo_da_tarefa: "VISITA",
            tipo_evento: "VISITA",
            data_agendamento: "2026-06-23T13:30:00",
            data_e_hora_agendamento: "2026-06-23T13:30:00",
            responsavel_pelo_evento: "Coord. Ana Julia",
            responsavel: "Coord. Ana Julia",
            telefone_contato: "(12) 99188-7766",
            numero_alunos: "200",
            numero_de_alunos: "200",
            valor_total: 3200,
            total: 3200,
            conteudo_da_apresentacao: "Sistema Solar 3D",
            finalizado: false,
            finalizada: false,
            precisa_voltar_para_base: false,
            latitude_origem: -23.5505,
            longitude_origem: -46.6333,
            latitude_destino: -23.0264,
            longitude_destino: -45.5552,
            origem_lat: -23.5505,
            origem_lon: -46.6333,
            destino_lat: -23.0264,
            destino_lon: -45.5552,
            distancia_estimada_km: 130,
            distancia: "130 km",
            id_astronomo: 1,
            observacoes: "Visita 1 da viagem Vale do Paraíba. Dormir na região (hospedagem necessária)."
        },
        {
            id: "ev_104",
            id_evento: "ev_104",
            nome_da_escola: "Colégio Newton",
            cidade: "Guaratinguetá - SP",
            cidade_destino: "Guaratinguetá - SP",
            tipo_da_tarefa: "VISITA",
            tipo_evento: "VISITA",
            data_agendamento: "2026-06-24T10:00:00",
            data_e_hora_agendamento: "2026-06-24T10:00:00",
            responsavel_pelo_evento: "Prof. André Santos",
            responsavel: "Prof. André Santos",
            telefone_contato: "(12) 98833-2211",
            numero_alunos: "150",
            numero_de_alunos: "150",
            valor_total: 2400,
            total: 2400,
            conteudo_da_apresentacao: "Vida das Estrelas",
            finalizado: false,
            finalizada: false,
            precisa_voltar_para_base: false,
            latitude_origem: -23.0264,
            longitude_origem: -45.5552, // Origem passa a ser Taubaté (evento anterior) na rota contínua
            latitude_destino: -22.8139,
            longitude_destino: -45.1925,
            origem_lat: -23.0264,
            origem_lon: -45.5552,
            destino_lat: -22.8139,
            destino_lon: -45.1925,
            distancia_estimada_km: 45,
            distancia: "45 km",
            id_astronomo: 1,
            observacoes: "Visita 2 da viagem Vale do Paraíba. Efetuar pernoite elegível para reembolso de hospedagem."
        },
        // --- Outro tipo de evento (Sem botões de finalizar) ---
        {
            id: "ev_105",
            id_evento: "ev_105",
            nome_da_escola: "Sede Urania",
            cidade: "São Paulo - SP",
            cidade_destino: "São Paulo - SP",
            tipo_da_tarefa: "TREINAMENTO",
            tipo_evento: "TREINAMENTO",
            data_agendamento: "2026-06-26T15:00:00",
            data_e_hora_agendamento: "2026-06-26T15:00:00",
            responsavel_pelo_evento: "Supervisora Clara",
            responsavel: "Supervisora Clara",
            telefone_contato: "(11) 98111-2222",
            numero_alunos: "0",
            numero_de_alunos: "0",
            valor_total: 0,
            total: 0,
            conteudo_da_apresentacao: "Novos Equipamentos H1",
            finalizado: false,
            finalizada: false,
            id_astronomo: 1,
            observacoes: "Treinamento prático com o novo projetor digital Urania."
        },

        // --- Históricos antigos (Finalizados em Maio de 2026) ---
        {
            id: "ev_h1",
            id_evento: "ev_h1",
            nome_da_escola: "Colégio Anglo Campinas",
            cidade: "Campinas - SP",
            cidade_destino: "Campinas - SP",
            tipo_da_tarefa: "VISITA",
            tipo_evento: "VISITA",
            data_agendamento: "2026-05-12T09:00:00",
            data_e_hora_agendamento: "2026-05-12T09:00:00",
            responsavel_pelo_evento: "Diretora Cecília",
            responsavel: "Diretora Cecília",
            telefone_contato: "(19) 99111-2233",
            numero_alunos: "180",
            numero_de_alunos: "180",
            valor_total: 2900,
            total: 2900,
            conteudo_da_apresentacao: "Foguetes e Órbitas",
            finalizado: true,
            finalizada: true,
            id_astronomo: 1,
            despesas_reais: { combustivel: 80, hospedagem: 0, alimentacao: 60, monitor: 120, pedagios: 24 },
            gastos_reais: 284,
            valor_liquido_astronomo: 435, // 15% de 2900
            avaliacao: "A apresentação foi fantástica. Os alunos ficaram muito empolgados e as demonstrações práticas de foguetes foram o ponto alto!",
            nota_npm: 10,
            npm: "Promotor"
        },
        {
            id: "ev_h2",
            id_evento: "ev_h2",
            nome_da_escola: "Escola Objetivo Santos",
            cidade: "Santos - SP",
            cidade_destino: "Santos - SP",
            tipo_da_tarefa: "VISITA",
            tipo_evento: "VISITA",
            data_agendamento: "2026-05-18T10:00:00",
            data_e_hora_agendamento: "2026-05-18T10:00:00",
            responsavel_pelo_evento: "Coordenador Flávio",
            responsavel: "Coordenador Flávio",
            telefone_contato: "(13) 98777-6655",
            numero_alunos: "90",
            numero_de_alunos: "90",
            valor_total: 2000,
            total: 2000,
            conteudo_da_apresentacao: "Constelações e Mitologia",
            finalizado: true,
            finalizada: true,
            id_astronomo: 1,
            despesas_reais: { combustivel: 120, hospedagem: 0, alimentacao: 60, monitor: 120, pedagios: 32 },
            gastos_reais: 332,
            valor_liquido_astronomo: 300, // 15% de 2000
            avaliacao: "Muito bom conteúdo, mas tivemos um pequeno atraso no início devido ao trânsito pesado na serra de Santos. No geral, foi bem positivo.",
            nota_npm: 7,
            npm: "Neutro"
        },
        {
            id: "ev_h3",
            id_evento: "ev_h3",
            nome_da_escola: "Colégio Pueri Domus",
            cidade: "São Paulo - SP",
            cidade_destino: "São Paulo - SP",
            tipo_da_tarefa: "VISITA",
            tipo_evento: "VISITA",
            data_agendamento: "2026-05-25T14:00:00",
            data_e_hora_agendamento: "2026-05-25T14:00:00",
            responsavel_pelo_evento: "Diretora Sandra",
            responsavel: "Diretora Sandra",
            telefone_contato: "(11) 97766-5544",
            numero_alunos: "250",
            numero_de_alunos: "250",
            valor_total: 3800,
            total: 3800,
            conteudo_da_apresentacao: "Sistema Solar 3D",
            finalizado: true,
            finalizada: true,
            id_astronomo: 1,
            despesas_reais: { combustivel: 15, hospedagem: 0, alimentacao: 60, monitor: 120, pedagios: 0 },
            gastos_reais: 195,
            valor_liquido_astronomo: 570, // 15% de 3800
            avaliacao: "O domo inflável do planetário móvel teve oscilação no ventilador de ar interno e fez um barulho incômodo durante o início da exibição.",
            nota_npm: 5,
            npm: "Detrator"
        }
    ]
};
